import { useState } from "react";
import { type Application, createPayment, fastForwardWait, issueLearnerLicence, saveApplicationDetails, submitApplication, submitLearnerTest, updateDocument } from "../api/client";

interface Props { application: Application; onUpdated: (application: Application) => void; onNavigate: (page: string) => void; }
const STATES: Record<string, string[]> = { Maharashtra: ["Pune West (MH-12)", "Mumbai Central (MH-01)"], Karnataka: ["Bengaluru Central (KA-01)"], Delhi: ["Sarai Kale Khan (DL-01)"], "Tamil Nadu": ["Chennai Central (TN-09)"] };
const QUESTIONS = [
  ["What does a solid red traffic light mean?", ["Slow down", "Stop and wait", "Proceed with caution", "Horn prohibited"], 1],
  ["What is the maximum speed limit in a residential area?", ["30 km/h", "40 km/h", "50 km/h", "60 km/h"], 0],
  ["When should you use your horn?", ["At all times", "Only to greet others", "Only when necessary, to warn others", "Never on highways"], 2],
  ["A yellow diamond road sign indicates:", ["Stop ahead", "Mandatory direction", "Warning / caution", "No entry"], 2],
  ["What does the 'No Parking' sign look like?", ["Red circle with a P", "Blue circle with a P", "Red cross on white", "Blue P crossed out"], 0],
] as const;

export default function ApplicationFlow({ application, onUpdated, onNavigate }: Props) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const act = async (work: () => Promise<{ application: Application }>) => { setBusy(true); setError(null); try { const result = await work(); onUpdated(result.application); } catch (error) { setError(error instanceof Error ? error.message : "We couldn't save your application right now."); } finally { setBusy(false); } };
  if (application.intent !== "first-ll") return <Frame title="Your Driving Licence journey"><p className="text-base text-gray-600 leading-relaxed">Your Learner's Licence path is safely saved. The full Driving Licence flow arrives in Phase 3.</p><Button onClick={() => onNavigate("dashboard")}>Back to My Journey</Button></Frame>;
  const step = application.currentStep;
  const props = { application, act, busy, error, onNavigate };
  if (step === "application-entry" || step === "eligibility") return <Location {...props} />;
  if (step === "personal-details") return <Personal {...props} />;
  if (step === "documents") return <Documents {...props} />;
  if (step === "fitness") return <Fitness {...props} />;
  if (step === "review") return <Review {...props} />;
  if (step === "payment") return <Payment {...props} />;
  if (step === "submitted" || step === "ll-preparation") return <Preparation {...props} />;
  if (step === "ll-test") return <LearnerTest {...props} />;
  if (step === "ll-result") return <Result {...props} />;
  if (step === "waiting-period") return <Waiting {...props} />;
  return <Preparation {...props} />;
}

type ScreenProps = { application: Application; busy: boolean; error: string | null; act: (work: () => Promise<{ application: Application }>) => Promise<void>; onNavigate: (page: string) => void; };
function Frame({ title, children, error }: { title: string; children: React.ReactNode; error?: string | null }) { return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-700 uppercase mb-3">Learner's Licence journey</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">{title}</h1>{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{children}</div></div>; }
function Button({ children, onClick, disabled = false, secondary = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; secondary?: boolean }) { return <button disabled={disabled} onClick={onClick} className={`mt-6 w-full rounded-xl px-5 py-3.5 text-base font-medium transition-colors disabled:opacity-50 ${secondary ? "border border-gray-200 text-gray-700 hover:bg-gray-50" : "bg-teal-600 text-white hover:bg-teal-700"}`}>{children}</button>; }
function Field({ label, value, set, type = "text", placeholder }: { label: string; value: string; set: (value: string) => void; type?: string; placeholder?: string }) { const fieldId = label.toLowerCase().replace(/[^a-z]+/g, "-"); return <label className="block mb-4 text-sm font-medium text-gray-700" htmlFor={fieldId}>{label}<input id={fieldId} type={type} value={value} placeholder={placeholder} onChange={(event) => set(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal text-gray-900 focus:outline-none focus:ring-2 focus:ring-teal-500" /></label>; }
function Note({ children }: { children: React.ReactNode }) { return <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-relaxed text-amber-800">{children}</p>; }

function Location({ application, busy, error, act }: ScreenProps) { const [state, setState] = useState(application.state || ""); const [rto, setRto] = useState(application.rto || ""); const [vehicle, setVehicle] = useState(String(application.details.vehicle || "")); const [dob, setDob] = useState(String(application.details.dob || "")); const valid = state && rto && vehicle && dob; return <Frame title="Where are you applying?" error={error}><p className="text-base leading-relaxed text-gray-600">Some requirements and online services may vary by state/RTO. This is demo information, not a live government lookup.</p><div className="mt-7"><label className="block mb-4 text-sm font-medium text-gray-700">State<select value={state} onChange={(event) => { setState(event.target.value); setRto(""); }} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Select state</option>{Object.keys(STATES).map((item) => <option key={item}>{item}</option>)}</select></label>{state && <label className="block mb-4 text-sm font-medium text-gray-700">RTO/location<select value={rto} onChange={(event) => setRto(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Select RTO</option>{STATES[state].map((item) => <option key={item}>{item}</option>)}</select></label>}<label className="block mb-4 text-sm font-medium text-gray-700">Vehicle class<select value={vehicle} onChange={(event) => setVehicle(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Choose vehicle class</option><option>LMV — Light Motor Vehicle</option><option>MCWG — Motorcycle with Gear</option><option>MCWOG — Motorcycle without Gear</option></select></label><Field label="Date of birth" type="date" value={dob} set={setDob} /></div><Button disabled={!valid || busy} onClick={() => act(() => saveApplicationDetails(application.id, { state, rto, vehicle, dob, eligibility: "ready", nextStep: "personal-details" }))}>{busy ? "Saving…" : "You're ready to continue →"}</Button></Frame>; }
function Personal({ application, busy, error, act }: ScreenProps) { const d = application.details; const [form, setForm] = useState({ name: String(d.name || ""), phone: String(d.phone || ""), email: String(d.email || ""), address: String(d.address || ""), city: String(d.city || ""), pin: String(d.pin || "") }); const set = (key: keyof typeof form) => (value: string) => setForm({ ...form, [key]: value }); const valid = form.name.trim() && /^\d{10}$/.test(form.phone.replace(/\D/g, "")) && form.address.trim() && form.city.trim() && /^\d{6}$/.test(form.pin); return <Frame title="Your personal details" error={error}><p className="text-base text-gray-600">Enter details exactly as they appear on your documents.</p><div className="mt-7"><Field label="Full name" value={form.name} set={set("name")} /><Field label="Mobile number" value={form.phone} set={(value) => setForm({ ...form, phone: value.replace(/\D/g, "").slice(0, 10) })} placeholder="9876543210" /><Field label="Email address (optional)" type="email" value={form.email} set={set("email")} /><Field label="Address" value={form.address} set={set("address")} /><Field label="City / District" value={form.city} set={set("city")} /><Field label="PIN code" value={form.pin} set={(value) => setForm({ ...form, pin: value.replace(/\D/g, "").slice(0, 6) })} /></div><Button disabled={!valid || busy} onClick={() => act(() => saveApplicationDetails(application.id, { ...form, nextStep: "documents" }))}>{busy ? "Saving…" : "Save and continue →"}</Button></Frame>; }
function Documents({ application, busy, error, act, onNavigate }: ScreenProps) { const docs = ["identity", "address", "photo-signature"] as const; const record = Object.fromEntries(application.documents.map((document) => [document.type, document.status])); const ready = docs.every((type) => ["ready", "replaced"].includes(record[type])); return <Frame title="Your documents" error={error}><p className="text-base leading-relaxed text-gray-600">Demo upload — no document is sent to a government system. Keep real documents out of this prototype.</p><div className="mt-7 space-y-3">{docs.map((type) => <div key={type} className="rounded-2xl border border-gray-200 p-4"><div className="flex justify-between gap-3"><div><h2 className="text-base font-semibold capitalize text-gray-900">{type.replace(/-/g, " ")}</h2><p className="mt-1 text-sm text-gray-600">PDF or JPG demo checklist · clear and readable.</p></div><span className="text-sm font-medium text-teal-700 capitalize">{record[type] || "needed"}</span></div>{record[type] === "rejected" ? <><Note>This document needs attention. Check that it is readable and matches the information entered above.</Note><Button disabled={busy} onClick={() => act(() => updateDocument(application.id, type, "replaced"))}>Replace document</Button></> : <Button disabled={busy} secondary onClick={() => act(() => updateDocument(application.id, type, record[type] === "ready" ? "rejected" : "ready"))}>{record[type] === "ready" ? "Simulate rejection / recovery" : "Mark demo document ready"}</Button>}</div>)}</div><Button disabled={!ready || busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "fitness" }))}>Continue to fitness →</Button><Button secondary onClick={() => onNavigate("dashboard")}>Back to My Journey</Button></Frame>; }
function Fitness({ application, busy, error, act }: ScreenProps) { const [checked, setChecked] = useState(Boolean(application.details.fitnessConfirmed)); return <Frame title="Fitness declaration" error={error}><p className="text-base leading-relaxed text-gray-600">Form 1 is a self-declaration in many cases. Form 1A may be required depending on your circumstances and state/RTO. Confirm the applicable requirement before a real application.</p><div className="mt-7 rounded-2xl bg-gray-50 p-5"><p className="text-base font-semibold text-gray-900">I understand this is a demo guide.</p><label className="mt-4 flex gap-3 text-sm leading-relaxed text-gray-700"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} className="mt-1 h-5 w-5 accent-teal-600" />I confirm the information I provided is correct to the best of my knowledge.</label></div><Button disabled={!checked || busy} onClick={() => act(() => saveApplicationDetails(application.id, { fitnessConfirmed: true, nextStep: "review" }))}>Confirm and review →</Button></Frame>; }
function Review({ application, busy, error, act }: ScreenProps) { const d = application.details; const docsReady = application.documents.length === 3 && application.documents.every((document) => ["ready", "replaced"].includes(document.status)); const [checked, setChecked] = useState(Boolean(d.reviewed)); return <Frame title="Review your application" error={error}><p className="text-base leading-relaxed text-gray-600">Check that the details you entered match your documents.</p><div className="mt-7 divide-y divide-gray-100 rounded-2xl border border-gray-200 p-4 text-sm"><Row label="State & RTO" value={`${application.state || "—"} · ${application.rto || "—"}`} /><Row label="Eligibility & vehicle" value={`${d.eligibility || "—"} · ${d.vehicle || "—"}`} /><Row label="Applicant" value={`${d.name || "—"} · ${d.dob || "—"}`} /><Row label="Contact" value={`${d.phone || "—"} · ${d.email || "No email"}`} /><Row label="Address" value={`${d.address || "—"}, ${d.city || "—"} ${d.pin || ""}`} /><Row label="Documents" value={docsReady ? "Ready" : "Action needed"} /><Row label="Fitness" value={d.fitnessConfirmed ? "Confirmed" : "Action needed"} /></div><label className="mt-5 flex gap-3 text-sm text-gray-700"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} className="h-5 w-5 accent-teal-600" />I have reviewed these details.</label><Button disabled={!checked || !docsReady || busy} onClick={() => act(() => saveApplicationDetails(application.id, { reviewed: true, nextStep: "payment" }))}>Continue to demo payment →</Button></Frame>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 py-3"><span className="text-gray-500">{label}</span><span className="text-right font-medium text-gray-900">{value}</span></div>; }
function Payment({ application, busy, error, act }: ScreenProps) { const [method, setMethod] = useState("UPI"); const [failure, setFailure] = useState(false); const payment = application.payment; if (payment?.status === "successful") return <Submitted {...{ application, busy, error, act, onNavigate: () => {} }} />; return <Frame title={payment?.status === "failed" ? "Payment wasn't confirmed" : "Demo payment"} error={error}>{payment?.status === "failed" ? <><Note>Do not pay again until you check the transaction status. This demo reference is {payment.reference}.</Note><Button disabled={busy} onClick={() => act(() => createPayment(application.id, method, "successful"))}>Retry demo payment →</Button></> : <><p className="text-base text-gray-600">Demo payment — no real money will be charged.</p><div className="mt-6 rounded-2xl border border-gray-200 p-5 text-sm"><Row label="Learner's Licence application" value="₹200" /><Row label="Theory test fee" value="₹50" /><Row label="Demo service charge" value="₹230" /><Row label="Total" value="₹480" /></div><div className="mt-5 space-y-2">{["UPI", "Card", "Net banking"].map((item) => <label key={item} className="flex items-center gap-3 rounded-xl border border-gray-200 px-4 py-3 text-sm"><input type="radio" checked={method === item} onChange={() => setMethod(item)} />{item}</label>)}</div><label className="mt-5 flex gap-3 text-sm text-gray-700"><input type="checkbox" checked={failure} onChange={(event) => setFailure(event.target.checked)} />Demo: simulate a failed payment first</label><Button disabled={busy} onClick={() => act(() => createPayment(application.id, method, failure ? "failed" : "successful"))}>{busy ? "Processing…" : "Pay ₹480 (simulated) →"}</Button></>}</Frame>; }
function Submitted({ application, busy, error, act }: ScreenProps) { return <Frame title="Application submitted" error={error}><p className="text-base text-gray-600">Your demo payment is recorded. Application reference: <strong>{application.id}</strong>.</p><div className="mt-7 rounded-2xl bg-teal-50 p-5 text-sm text-teal-900"><p>✓ Application prepared</p><p className="mt-2">✓ Payment</p><p className="mt-2 font-semibold">● Learner's Licence stage</p></div><Button disabled={busy} onClick={() => act(() => submitApplication(application.id))}>Prepare for your Learner's Licence test →</Button></Frame>; }
function Preparation({ application, busy, error, act }: ScreenProps) { return <Frame title="Prepare for your Learner's Licence test" error={error}><p className="text-base leading-relaxed text-gray-600">Learn road signs and safe driving rules, then take a short five-question demo test. This does not replace an official test or RTO requirement.</p><div className="mt-7 space-y-3"><Info title="Learn" text="Review road signs, traffic lights, and safe road behaviour." /><Info title="Practice" text="The test has five multiple-choice practice questions." /><Info title="Safety" text="Take a break and use the official/state resources for current requirements." /></div><Button disabled={busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "ll-test" }))}>Start learner test →</Button></Frame>; }
function Info({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-gray-200 p-4"><h2 className="font-semibold text-gray-900">{title}</h2><p className="mt-1 text-sm leading-relaxed text-gray-600">{text}</p></div>; }
function LearnerTest({ application, busy, error, act }: ScreenProps) { const [answers, setAnswers] = useState<number[]>(Array(5).fill(-1)); const [index, setIndex] = useState(0); const question = QUESTIONS[index]; return <Frame title="Learner's Licence test" error={error}><p className="text-base text-gray-600">Question {index + 1} of {QUESTIONS.length}. Choose an answer; you can return to earlier questions.</p><div className="mt-7"><h2 className="text-lg font-semibold text-gray-900">{question[0]}</h2><div className="mt-4 space-y-2">{question[1].map((option, optionIndex) => <button key={option} onClick={() => { const next = [...answers]; next[index] = optionIndex; setAnswers(next); }} className={`w-full rounded-xl border px-4 py-3 text-left text-base ${answers[index] === optionIndex ? "border-teal-500 bg-teal-50 text-teal-900" : "border-gray-200 text-gray-700 hover:bg-gray-50"}`}>{option}</button>)}</div></div><div className="mt-6 flex gap-3"><button disabled={index === 0} onClick={() => setIndex(index - 1)} className="rounded-xl border border-gray-200 px-4 py-3 text-sm disabled:opacity-40">Previous</button>{index < 4 ? <button onClick={() => setIndex(index + 1)} className="rounded-xl bg-teal-600 px-4 py-3 text-sm font-medium text-white">Next</button> : <button disabled={answers.includes(-1) || busy} onClick={() => act(() => submitLearnerTest(application.id, answers))} className="rounded-xl bg-teal-600 px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit answers"}</button>}</div></Frame>; }
function Result({ application, busy, error, act }: ScreenProps) { const test = application.test; if (!test) return <Preparation {...{ application, busy, error, act, onNavigate: () => {} }} />; if (!test.passed) return <Frame title="You have another attempt ahead" error={error}><p className="text-base leading-relaxed text-gray-600">You scored {test.score} of {test.total}. That’s okay—review the road signs and safety preparation, then try again when you’re ready.</p><Button disabled={busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "ll-preparation" }))}>Practice again →</Button></Frame>; return <Frame title="You've completed your Learner's Licence test" error={error}><p className="text-base leading-relaxed text-gray-600">You scored {test.score} of {test.total}. Your LL stage is ready for the demo issue record.</p><Note>The next real-world steps and availability can vary by state/RTO.</Note><Button disabled={busy} onClick={() => act(() => issueLearnerLicence(application.id))}>Issue Learner's Licence — Demo →</Button></Frame>; }
function Waiting({ application, busy, error, act, onNavigate }: ScreenProps) { const licence = application.licence; if (!licence) return <Result {...{ application, busy, error, act, onNavigate }} />; const days = Math.max(0, Math.ceil((new Date(licence.eligibleForDlAt).getTime() - Date.now()) / 86400000)); return <Frame title="Learner's Licence issued — Demo" error={error}><div className="rounded-2xl border border-teal-200 bg-teal-50 p-5"><p className="text-xs font-semibold tracking-widest text-teal-700">SIMULATED LICENCE RECORD</p><h2 className="mt-2 text-xl font-semibold text-teal-900">{licence.reference}</h2><p className="mt-2 text-sm leading-relaxed text-teal-900">{application.details.name || "Demo applicant"} · {application.details.vehicle || "Vehicle class"}<br />Validity: 6 months (until {new Date(licence.validUntil).toLocaleDateString()})</p></div><button onClick={() => window.print()} className="mt-4 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Print / Download demo</button><div className="mt-6 rounded-2xl bg-gray-50 p-5"><p className="text-sm text-gray-500">Your next milestone</p><h2 className="mt-1 text-2xl font-semibold text-gray-900">{days === 0 ? "Eligible for DL — demo" : `${days} days remaining`}</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">You can continue to prepare while you wait. The Driving Licence application itself begins in Phase 3.</p></div>{days > 0 && <Button secondary disabled={busy} onClick={() => act(() => fastForwardWait(application.id))}>Developer demo: fast-forward waiting period</Button>}<Button secondary onClick={() => onNavigate("dashboard")}>Return to My Journey</Button></Frame>; }
