import { useState } from "react";
import { type Application, createPayment, fastForwardWait, issueLearnerLicence, saveApplicationDetails, startDl, submitApplication, submitLearnerTest, updateDocument } from "../api/client";
import { LEARNER_QUESTIONS } from "../data/learnerQuestions";
import { STATES, VEHICLES, applyTarget, eligibilityResult, needsMedicalFitness, waitingDays } from "../journey";
import DrivingLicenceFlow from "./DrivingLicenceFlow";

interface Props { application: Application; onUpdated: (application: Application) => void; onNavigate: (page: string) => void; focus?: string; }

export default function ApplicationFlow({ application, onUpdated, onNavigate, focus }: Props) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [returnToReview, setReturnToReview] = useState(false);
  const act = async (work: () => Promise<{ application: Application }>) => { setBusy(true); setError(null); try { const result = await work(); onUpdated(result.application); } catch (error) { setError(error instanceof Error ? error.message : "We couldn't save your application right now."); } finally { setBusy(false); } };
  const step = applyTarget(application, focus);
  
  // Handle gated panels that require user to apply first
  if (step === "documents-apply-first") return <PanelGate panelName="Documents" onNavigate={onNavigate} />;
  if (step === "payment-apply-first") return <PanelGate panelName="Payments" onNavigate={onNavigate} />;
  if (step === "appointment-apply-first") return <PanelGate panelName="Appointments" onNavigate={onNavigate} />;
  if (step === "payment-view") return <PaymentHistory application={application} onNavigate={onNavigate} />;
  if (step === "appointment-view") return <AppointmentHistory application={application} onNavigate={onNavigate} />;
  
  if (application.intent === "existing-ll" && step !== "existing-ll-details" && !step.endsWith("-apply-first")) return <DrivingLicenceFlow application={application} onUpdated={onUpdated} onNavigate={onNavigate} focus={focus} />;
  if (application.intent === "first-ll" && (step.startsWith("dl-") || application.currentStep.startsWith("dl-"))) return <DrivingLicenceFlow application={application} onUpdated={onUpdated} onNavigate={onNavigate} focus={focus} />;
  const props = { application, act, busy, error, onNavigate, returnToReview, setReturnToReview };
  if (step === "existing-ll-details") return <ExistingLl {...props} />;
  if (step === "application-entry" || step === "state-rto") return <Location {...props} />;
  if (step === "eligibility") return <Eligibility {...props} />;
  if (step === "personal-details") return <Personal {...props} />;
  if (step === "documents") return focus === "documents"
    ? <DocumentRecord application={application} onNavigate={onNavigate} />
    : <Documents {...props} />;
  if (step === "fitness") return <Fitness {...props} />;
  if (step === "review") return <Review {...props} />;
  if (step === "payment") return <Payment {...props} />;
  if (step === "submitted") return <Submitted {...props} />;
  if (step === "ll-preparation") return <Preparation {...props} />;
  if (step === "ll-test") return <LearnerTest {...props} />;
  if (step === "ll-result") return <Result {...props} />;
  if (step === "ll-issued") return <Issued {...props} />;
  if (step === "waiting-period") return <Waiting {...props} />;
  if (step === "dl-eligible") return <DlEligible {...props} />;
  return <Location {...props} />;
}

// Gate component shown when panel requirements are not met
function PanelGate({ panelName, onNavigate }: { panelName: string; onNavigate: (page: string, data?: unknown) => void }) {
  return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-700 uppercase mb-3">Application required</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">{panelName} panel</h1><p className="text-base text-gray-600 mb-8">Please apply for your licence first.</p><button onClick={() => onNavigate("dashboard")} className="w-full px-5 py-3.5 bg-teal-600 text-white font-medium rounded-xl hover:bg-teal-700 transition-colors text-base">Apply for licence →</button></div></div>;
}

// View component for displaying saved payment information
function PaymentHistory({ application, onNavigate }: { application: Application; onNavigate: (page: string) => void }) {
  const payment = application.intent === "existing-ll" ? application.dl?.payment : application.payment;
  return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-700 uppercase mb-3">Learner's Licence journey</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">Your payment record</h1>{payment ? <><div className="mt-7 rounded-2xl border border-gray-200 p-5 text-sm space-y-3"><div className="flex justify-between"><span className="text-gray-500">Payment reference:</span><span className="font-medium text-gray-900">{payment.reference}</span></div><div className="flex justify-between"><span className="text-gray-500">Method:</span><span className="font-medium text-gray-900">{payment.method}</span></div><div className="flex justify-between"><span className="text-gray-500">Amount:</span><span className="font-medium text-gray-900">₹{payment.amount}</span></div><div className="flex justify-between"><span className="text-gray-500">Status:</span><span className="font-medium capitalize" style={{color: payment.status === "successful" ? "#059669" : "#dc2626"}}>{payment.status}</span></div></div><button onClick={() => window.print()} className="mt-6 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Print / Download record</button></> : <p className="text-base text-gray-600 mt-7">No payment record found yet.</p>}<button onClick={() => onNavigate("dashboard")} className="mt-6 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Back to My Journey</button></div></div>;
}

function AppointmentHistory({ application, onNavigate }: { application: Application; onNavigate: (page: string) => void }) {
  const appointment = application.dl?.appointment;
  return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-700 uppercase mb-3">Driving Licence journey</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">Your appointment record</h1>{appointment ? <><div className="mt-7 rounded-2xl border border-gray-200 p-5 text-sm space-y-3"><div className="flex justify-between"><span className="text-gray-500">RTO:</span><span className="font-medium text-gray-900">{application.dl?.data.rto || application.rto || "—"}</span></div><div className="flex justify-between"><span className="text-gray-500">Slot:</span><span className="font-medium text-gray-900">{appointment.slot}</span></div><div className="flex justify-between"><span className="text-gray-500">Status:</span><span className="font-medium capitalize text-emerald-600">{appointment.status}</span></div></div><button onClick={() => window.print()} className="mt-6 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Print / Download record</button></> : null}<button onClick={() => onNavigate("dashboard")} className="mt-6 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Back to My Journey</button></div></div>;
}

function DocumentRecord({ application, onNavigate }: { application: Application; onNavigate: (page: string) => void }) {
  const details = application.details;
  return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-700 uppercase mb-3">Saved application</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">Your documents</h1><p className="text-base text-gray-600">Read-only information from your saved application.</p><div className="mt-7 rounded-2xl border border-gray-200 p-5 text-sm space-y-3"><div className="flex justify-between"><span className="text-gray-500">Applicant:</span><span className="font-medium text-gray-900">{details.name || "—"}</span></div><div className="flex justify-between"><span className="text-gray-500">State / RTO:</span><span className="font-medium text-gray-900">{application.state || "—"} · {application.rto || "—"}</span></div>{application.documents.map((document) => <div key={document.type} className="flex justify-between"><span className="capitalize text-gray-500">{document.type.replace(/-/g, " ")}:</span><span className="font-medium capitalize text-gray-900">{document.status}</span></div>)}</div><button onClick={() => window.print()} className="mt-6 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Print / Download record</button><button onClick={() => onNavigate("dashboard")} className="mt-3 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Back to My Journey</button></div></div>;
}

type ScreenProps = { application: Application; busy: boolean; error: string | null; act: (work: () => Promise<{ application: Application }>) => Promise<void>; onNavigate: (page: string) => void; returnToReview: boolean; setReturnToReview: (value: boolean) => void; };
function Frame({ title, children, error }: { title: string; children: React.ReactNode; error?: string | null }) { return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-700 uppercase mb-3">Learner&apos;s Licence journey</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">{title}</h1>{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{children}</div></div>; }
function Button({ children, onClick, disabled = false, secondary = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; secondary?: boolean }) { return <button disabled={disabled} onClick={onClick} className={`mt-6 w-full rounded-xl px-5 py-3.5 text-base font-medium transition-colors disabled:opacity-50 ${secondary ? "border border-gray-200 text-gray-700 hover:bg-gray-50" : "bg-teal-600 text-white hover:bg-teal-700"}`}>{children}</button>; }
function Field({ label, value, set, type = "text", placeholder }: { label: string; value: string; set: (value: string) => void; type?: string; placeholder?: string }) { const fieldId = label.toLowerCase().replace(/[^a-z]+/g, "-"); return <label className="block mb-4 text-sm font-medium text-gray-700" htmlFor={fieldId}>{label}<input id={fieldId} type={type} value={value} placeholder={placeholder} onChange={(event) => set(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal text-gray-900 focus:outline-none focus:ring-2 focus:ring-teal-500" /></label>; }
function Note({ children }: { children: React.ReactNode }) { return <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-relaxed text-amber-800">{children}</p>; }
function nextAfter(returnToReview: boolean, fallback: string) { return returnToReview ? "review" : fallback; }

function Location({ application, busy, error, act, returnToReview }: ScreenProps) {
  const [state, setState] = useState(application.state || ""); const [rto, setRto] = useState(application.rto || "");
  return <Frame title="Where are you applying?" error={error}><p className="text-base leading-relaxed text-gray-600">Some requirements and online services may vary by state/RTO. This is demo information, not a live government lookup.</p><div className="mt-7"><label className="block mb-4 text-sm font-medium text-gray-700">State<select value={state} onChange={(event) => { setState(event.target.value); setRto(""); }} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Select state</option>{Object.keys(STATES).map((item) => <option key={item}>{item}</option>)}</select></label>{state && <label className="block mb-4 text-sm font-medium text-gray-700">RTO/location<select value={rto} onChange={(event) => setRto(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Select RTO</option>{STATES[state].map((item) => <option key={item}>{item}</option>)}</select></label>}</div><Button disabled={!state || !rto || busy} onClick={() => act(() => saveApplicationDetails(application.id, { state, rto, nextStep: nextAfter(returnToReview, "eligibility") }))}>{busy ? "Saving…" : "Continue to eligibility →"}</Button></Frame>;
}

function Eligibility({ application, busy, error, act, returnToReview }: ScreenProps) {
  const [vehicle, setVehicle] = useState(String(application.details.vehicle || "")); const [dob, setDob] = useState(String(application.details.dob || ""));
  const result = eligibilityResult(dob, vehicle);
  return <Frame title="Demo eligibility check" error={error}><p className="text-base leading-relaxed text-gray-600">This check uses simple demo rules. It does not replace an official determination by your state/RTO.</p><div className="mt-7"><label className="block mb-4 text-sm font-medium text-gray-700">Vehicle class<select value={vehicle} onChange={(event) => setVehicle(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Choose vehicle class</option>{VEHICLES.map((item) => <option key={item}>{item}</option>)}</select></label><Field label="Date of birth" type="date" value={dob} set={setDob} /></div>{vehicle && dob && <Note>{result.summary} Motorcycle without gear is usually 16+ in this demo; other classes are 18+.</Note>}<Button disabled={!result.ready || busy} onClick={() => act(() => saveApplicationDetails(application.id, { vehicle, dob, eligibility: result.ready ? "ready" : "not-ready", nextStep: nextAfter(returnToReview, "personal-details") }))}>{busy ? "Saving…" : result.ready ? "You're ready to continue →" : "Not eligible in this demo yet"}</Button></Frame>;
}

function Personal({ application, busy, error, act, returnToReview }: ScreenProps) {
  const d = application.details; const [form, setForm] = useState({ name: String(d.name || ""), phone: String(d.phone || ""), email: String(d.email || ""), address: String(d.address || ""), city: String(d.city || ""), pin: String(d.pin || "") });
  const set = (key: keyof typeof form) => (value: string) => setForm({ ...form, [key]: value });
  const valid = form.name.trim() && /^\d{10}$/.test(form.phone.replace(/\D/g, "")) && form.address.trim() && form.city.trim() && /^\d{6}$/.test(form.pin);
  return <Frame title="Your personal details" error={error}><p className="text-base text-gray-600">Enter details exactly as they appear on your documents.</p><div className="mt-7"><Field label="Full name" value={form.name} set={set("name")} /><Field label="Mobile number" value={form.phone} set={(value) => setForm({ ...form, phone: value.replace(/\D/g, "").slice(0, 10) })} placeholder="9876543210" /><Field label="Email address (optional)" type="email" value={form.email} set={set("email")} /><Field label="Address" value={form.address} set={set("address")} /><Field label="City / District" value={form.city} set={set("city")} /><Field label="PIN code" value={form.pin} set={(value) => setForm({ ...form, pin: value.replace(/\D/g, "").slice(0, 6) })} /></div><Button disabled={!valid || busy} onClick={() => act(() => saveApplicationDetails(application.id, { ...form, nextStep: nextAfter(returnToReview, "documents") }))}>{busy ? "Saving…" : "Save and continue →"}</Button></Frame>;
}

function Documents({ application, busy, error, act, onNavigate, returnToReview }: ScreenProps) {
  const docs = ["identity", "address", "photo-signature"] as const;
  const record = Object.fromEntries(application.documents.map((document) => [document.type, document.status]));
  const ready = docs.every((type) => ["ready", "replaced"].includes(record[type]));
  return <Frame title="Your documents" error={error}><p className="text-base leading-relaxed text-gray-600">Demo checklist — no document is sent to a government system. Keep real documents out of this prototype.</p><div className="mt-7 space-y-3">{docs.map((type) => <div key={type} className="rounded-2xl border border-gray-200 p-4"><div className="flex justify-between gap-3"><div><h2 className="text-base font-semibold capitalize text-gray-900">{type.replace(/-/g, " ")}</h2><p className="mt-1 text-sm text-gray-600">PDF or JPG · clear, readable, matching your details. Exact lists vary by state/RTO.</p></div><span className="text-sm font-medium text-teal-700 capitalize">{record[type] || "needed"}</span></div>{record[type] === "rejected" ? <><Note>This document needs attention. Check that it is readable and matches the information entered above.</Note><Button disabled={busy} onClick={() => act(() => updateDocument(application.id, type, "replaced"))}>Replace document</Button></> : <Button disabled={busy} secondary onClick={() => act(() => updateDocument(application.id, type, record[type] === "ready" ? "rejected" : "ready"))}>{record[type] === "ready" ? "Demo: mark as rejected" : "Mark demo document ready"}</Button>}</div>)}</div><Button disabled={!ready || busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: nextAfter(returnToReview, "fitness") }))}>Continue →</Button><Button secondary onClick={() => onNavigate("dashboard")}>Back to My Journey</Button></Frame>;
}

function Fitness({ application, busy, error, act, returnToReview }: ScreenProps) {
  const medical = needsMedicalFitness(String(application.details.dob || ""));
  const [checked, setChecked] = useState(Boolean(application.details.fitnessConfirmed));
  return <Frame title="Fitness declaration" error={error}><p className="text-base leading-relaxed text-gray-600">{medical ? "Because of the age you entered, Form 1A (a medical certificate) may be required. Confirm the applicable requirement with your state/RTO before a real application." : "Form 1 is a self-declaration of physical fitness in many non-transport cases. Form 1A may still be required depending on your circumstances and state/RTO."}</p><div className="mt-7 rounded-2xl bg-gray-50 p-5"><p className="text-base font-semibold text-gray-900">{medical ? "Form 1A — medical certificate may apply" : "Form 1 — self-declaration"}</p><p className="mt-2 text-sm leading-relaxed text-gray-600">This is demo guidance, not medical or legal advice.</p><label className="mt-4 flex gap-3 text-sm leading-relaxed text-gray-700"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} className="mt-1 h-5 w-5 accent-teal-600" />I confirm I understand this demo fitness step and will check the real requirement with my RTO.</label></div><Button disabled={!checked || busy} onClick={() => act(() => saveApplicationDetails(application.id, { fitnessConfirmed: true, nextStep: nextAfter(returnToReview, "review") }))}>Confirm and review →</Button></Frame>;
}

function Review({ application, busy, error, act, setReturnToReview }: ScreenProps) {
  const d = application.details;
  const docsReady = application.documents.length === 3 && application.documents.every((document) => ["ready", "replaced"].includes(document.status));
  const [checked, setChecked] = useState(Boolean(d.reviewed));
  const edit = (step: string) => { setReturnToReview(true); void act(() => saveApplicationDetails(application.id, { nextStep: step })); };
  return <Frame title="Review your application" error={error}><p className="text-base leading-relaxed text-gray-600">Check that the details you entered match your documents. Use Edit to change a section; you will come back here.</p><div className="mt-7 divide-y divide-gray-100 rounded-2xl border border-gray-200 p-4 text-sm"><Row label="State & RTO" value={`${application.state || "—"} · ${application.rto || "—"}`} onEdit={() => edit("application-entry")} /><Row label="Eligibility & vehicle" value={`${d.eligibility || "—"} · ${d.vehicle || "—"}`} onEdit={() => edit("eligibility")} /><Row label="Applicant" value={`${d.name || "—"} · ${d.dob || "—"}`} onEdit={() => edit("personal-details")} /><Row label="Contact" value={`${d.phone || "—"} · ${d.email || "No email"}`} onEdit={() => edit("personal-details")} /><Row label="Address" value={`${d.address || "—"}, ${d.city || "—"} ${d.pin || ""}`} onEdit={() => edit("personal-details")} /><Row label="Documents" value={docsReady ? "Ready" : "Action needed"} onEdit={() => edit("documents")} /><Row label="Fitness" value={d.fitnessConfirmed ? "Confirmed" : "Action needed"} onEdit={() => edit("fitness")} /></div><label className="mt-5 flex gap-3 text-sm text-gray-700"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} className="h-5 w-5 accent-teal-600" />I have reviewed these details.</label><Button disabled={!checked || !docsReady || busy} onClick={() => { setReturnToReview(false); void act(() => saveApplicationDetails(application.id, { reviewed: true, nextStep: "payment" })); }}>Continue to demo payment →</Button></Frame>;
}

function Row({ label, value, onEdit }: { label: string; value: string; onEdit?: () => void }) {
  return <div className="flex justify-between gap-4 py-3 items-start"><span className="text-gray-500">{label}</span><span className="text-right"><span className="font-medium text-gray-900">{value}</span>{onEdit && <button type="button" onClick={onEdit} className="ml-3 text-teal-700 font-medium">Edit</button>}</span></div>;
}

function Payment({ application, busy, error, act }: ScreenProps) {
  const [method, setMethod] = useState("UPI"); const [failure, setFailure] = useState(false); const payment = application.payment;
  return <Frame title={payment?.status === "failed" ? "Payment wasn't confirmed" : "Demo payment"} error={error}>{payment?.status === "failed" ? <div className="print-record"><Note>Do not pay again until you check the transaction status. This demo reference is {payment.reference}.</Note><Button disabled={busy} onClick={() => act(() => createPayment(application.id, method, "successful"))}>Retry demo payment →</Button></div> : <><p className="text-base text-gray-600">Demo payment — no real money will be charged. Amounts are fictional and can vary by state/RTO.</p><div className="mt-6 rounded-2xl border border-gray-200 p-5 text-sm print-record"><Row label="Learner's Licence application" value="₹200" /><Row label="Theory test fee" value="₹50" /><Row label="Demo service charge" value="₹230" /><Row label="Total" value="₹480" /></div><div className="mt-5 space-y-2">{["UPI", "Card", "Net banking"].map((item) => <label key={item} className="flex items-center gap-3 rounded-xl border border-gray-200 px-4 py-3 text-sm"><input type="radio" checked={method === item} onChange={() => setMethod(item)} />{item}</label>)}</div><label className="mt-5 flex gap-3 text-sm text-gray-700"><input type="checkbox" checked={failure} onChange={(event) => setFailure(event.target.checked)} />Demo: simulate a failed payment first</label><Button disabled={busy} onClick={() => act(() => createPayment(application.id, method, failure ? "failed" : "successful"))}>{busy ? "Processing…" : "Pay ₹480 (simulated) →"}</Button></>}</Frame>;
}

function Submitted({ application, busy, error, act }: ScreenProps) {
  return <Frame title="Application submitted" error={error}><div className="print-record"><p className="text-base text-gray-600">Your demo payment is recorded. Application reference: <strong>{application.id}</strong>.</p>{application.payment && <p className="mt-2 text-sm text-gray-600">Payment reference: {application.payment.reference} · {application.payment.method} · ₹{application.payment.amount}</p>}<div className="mt-7 rounded-2xl bg-teal-50 p-5 text-sm text-teal-900"><p>✓ Application prepared</p><p className="mt-2">✓ Payment</p><p className="mt-2 font-semibold">● Submitted — Learner&apos;s Licence stage</p></div></div><button onClick={() => window.print()} className="mt-4 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Print payment receipt</button><Button disabled={busy} onClick={() => act(() => submitApplication(application.id))}>Prepare for your Learner&apos;s Licence test →</Button></Frame>;
}

function Preparation({ application, busy, error, act }: ScreenProps) { return <Frame title="Prepare for your Learner's Licence test" error={error}><p className="text-base leading-relaxed text-gray-600">Learn road signs and safe driving rules, then take a short five-question demo test. This does not replace an official test or RTO requirement.</p><div className="mt-7 space-y-3"><Info title="Learn" text="Review road signs, traffic lights, and safe road behaviour." /><Info title="Practice" text="Use the Resources practice test first if you want. It does not affect this scored demo test." /><Info title="Safety" text="Take a break and use official/state resources for current requirements." /></div><Button disabled={busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "ll-test" }))}>Start learner test →</Button></Frame>; }
function Info({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-gray-200 p-4"><h2 className="font-semibold text-gray-900">{title}</h2><p className="mt-1 text-sm leading-relaxed text-gray-600">{text}</p></div>; }

function LearnerTest({ application, busy, error, act }: ScreenProps) {
  const [answers, setAnswers] = useState<number[]>(Array(5).fill(-1)); const [index, setIndex] = useState(0); const question = LEARNER_QUESTIONS[index];
  return <Frame title="Learner's Licence test" error={error}><p className="text-base text-gray-600">Question {index + 1} of {LEARNER_QUESTIONS.length}. Choose an answer; you can return to earlier questions. This scored test is separate from the practice quiz in Resources.</p><div className="mt-7"><h2 className="text-lg font-semibold text-gray-900">{question[0]}</h2><div className="mt-4 space-y-2">{question[1].map((option, optionIndex) => <button key={option} onClick={() => { const next = [...answers]; next[index] = optionIndex; setAnswers(next); }} className={`w-full rounded-xl border px-4 py-3 text-left text-base ${answers[index] === optionIndex ? "border-teal-500 bg-teal-50 text-teal-900" : "border-gray-200 text-gray-700 hover:bg-gray-50"}`}>{option}</button>)}</div></div><div className="mt-6 flex gap-3"><button disabled={index === 0} onClick={() => setIndex(index - 1)} className="rounded-xl border border-gray-200 px-4 py-3 text-sm disabled:opacity-40">Previous</button>{index < 4 ? <button disabled={answers[index] < 0} onClick={() => setIndex(index + 1)} className="rounded-xl bg-teal-600 px-4 py-3 text-sm font-medium text-white disabled:opacity-50">Next</button> : <button disabled={answers.includes(-1) || busy} onClick={() => act(() => submitLearnerTest(application.id, answers))} className="rounded-xl bg-teal-600 px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit answers"}</button>}</div></Frame>;
}

function Result({ application, busy, error, act }: ScreenProps) {
  const test = application.test;
  if (!test) return <Preparation {...{ application, busy, error, act, onNavigate: () => {}, returnToReview: false, setReturnToReview: () => {} }} />;
  if (!test.passed) return <Frame title="You have another attempt ahead" error={error}><p className="text-base leading-relaxed text-gray-600">You scored {test.score} of {test.total}. That&apos;s okay—review the road signs and safety preparation, then try again when you&apos;re ready.</p><Button disabled={busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "ll-preparation" }))}>Practice again →</Button></Frame>;
  return <Frame title="You've completed your Learner's Licence test" error={error}><p className="text-base leading-relaxed text-gray-600">You scored {test.score} of {test.total}. Your LL stage is ready for the demo issue record.</p><Note>The next real-world steps and availability can vary by state/RTO.</Note><Button disabled={busy} onClick={() => act(() => issueLearnerLicence(application.id))}>Issue Learner&apos;s Licence — Demo →</Button></Frame>;
}

function Issued({ application, busy, error, act, onNavigate }: ScreenProps) {
  const licence = application.licence;
  if (!licence) return <Result {...{ application, busy, error, act, onNavigate, returnToReview: false, setReturnToReview: () => {} }} />;
  return <Frame title="Learner's Licence issued — Demo" error={error}><div className="print-record rounded-2xl border border-teal-200 bg-teal-50 p-5"><p className="text-xs font-semibold tracking-widest text-teal-700">SIMULATED LICENCE RECORD</p><h2 className="mt-2 text-xl font-semibold text-teal-900">{licence.reference}</h2><p className="mt-2 text-sm leading-relaxed text-teal-900">{application.details.name || "Demo applicant"} · {application.details.vehicle || "Vehicle class"}<br />Validity: 6 months (until {new Date(licence.validUntil).toLocaleDateString()})</p></div><button onClick={() => window.print()} className="mt-4 w-full rounded-xl border border-gray-200 px-5 py-3 text-sm font-medium text-gray-700">Print / Download demo</button><Button disabled={busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "waiting-period" }))}>See the 30-day waiting period →</Button><Button secondary onClick={() => onNavigate("dashboard")}>Return to My Journey</Button></Frame>;
}

function Waiting({ application, busy, error, act, onNavigate }: ScreenProps) {
  const licence = application.licence;
  if (!licence) return <Issued {...{ application, busy, error, act, onNavigate, returnToReview: false, setReturnToReview: () => {} }} />;
  const days = waitingDays(application);
  return <Frame title="30-day waiting period" error={error}><div className="rounded-2xl bg-gray-50 p-5"><p className="text-sm text-gray-500">Your next milestone</p><h2 className="mt-1 text-2xl font-semibold text-gray-900">{days === 0 ? "You can now apply for your Driving Licence" : `${days} days remaining`}</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">Practise safely. Your Learner&apos;s Licence remains valid for 6 months in this demo. Actual timing varies by state/RTO.</p></div>{days === 0 && <Button disabled={busy} onClick={() => act(() => saveApplicationDetails(application.id, { nextStep: "dl-eligible" }))}>Continue to Driving Licence eligibility →</Button>}<Button secondary onClick={() => onNavigate("dashboard")}>Return to My Journey</Button><DemoTools busy={busy} onFastForward={() => act(() => fastForwardWait(application.id))} /></Frame>;
}

function DlEligible({ application, busy, error, act }: ScreenProps) {
  return <Frame title="You can apply for your Driving Licence" error={error}><p className="text-base leading-relaxed text-gray-600">Your simulated waiting period is complete. We will carry forward your learner details so you do not enter them twice.</p><Button disabled={busy} onClick={() => act(() => startDl(application.id))}>Start Driving Licence application →</Button></Frame>;
}

function ExistingLl({ application, busy, error, act }: ScreenProps) {
  const d = application.details;
  const [form, setForm] = useState({ learnerReference: String(d.learnerReference || ""), llIssueDate: String(d.llIssueDate || "").slice(0, 10), vehicle: String(d.vehicle || ""), name: String(d.name || ""), phone: String(d.phone || ""), address: String(d.address || ""), city: String(d.city || ""), pin: String(d.pin || ""), dob: String(d.dob || "") });
  const [state, setState] = useState(application.state || ""); const [rto, setRto] = useState(application.rto || "");
  const valid = form.learnerReference.trim().length >= 4 && form.llIssueDate && form.vehicle && form.name.trim() && /^\d{10}$/.test(form.phone.replace(/\D/g, "")) && form.address.trim() && state && rto;
  return <Frame title="Confirm your existing Learner's Licence" error={error}><p className="text-base leading-relaxed text-gray-600">Enter the details from your current learner record. Use a demo reference if you are exploring the prototype — do not enter a real government number unless you are comfortable, and remember this is not sent to any RTO.</p><div className="mt-7"><Field label="Learner's Licence number / reference" value={form.learnerReference} set={(value) => setForm({ ...form, learnerReference: value })} placeholder="LL-XXXX-XXXX" /><Field label="LL issue date" type="date" value={form.llIssueDate} set={(value) => setForm({ ...form, llIssueDate: value })} /><label className="block mb-4 text-sm font-medium text-gray-700">Vehicle class<select value={form.vehicle} onChange={(event) => setForm({ ...form, vehicle: event.target.value })} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Choose vehicle class</option>{VEHICLES.map((item) => <option key={item}>{item}</option>)}</select></label><Field label="Full name" value={form.name} set={(value) => setForm({ ...form, name: value })} /><Field label="Date of birth" type="date" value={form.dob} set={(value) => setForm({ ...form, dob: value })} /><Field label="Mobile number" value={form.phone} set={(value) => setForm({ ...form, phone: value.replace(/\D/g, "").slice(0, 10) })} /><Field label="Address" value={form.address} set={(value) => setForm({ ...form, address: value })} /><Field label="City / District" value={form.city} set={(value) => setForm({ ...form, city: value })} /><Field label="PIN code" value={form.pin} set={(value) => setForm({ ...form, pin: value.replace(/\D/g, "").slice(0, 6) })} /><label className="block mb-4 text-sm font-medium text-gray-700">State<select value={state} onChange={(event) => { setState(event.target.value); setRto(""); }} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Select state</option>{Object.keys(STATES).map((item) => <option key={item}>{item}</option>)}</select></label>{state && <label className="block mb-4 text-sm font-medium text-gray-700">RTO<select value={rto} onChange={(event) => setRto(event.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal"><option value="">Select RTO</option>{STATES[state].map((item) => <option key={item}>{item}</option>)}</select></label>}</div><Button disabled={!valid || busy} onClick={() => act(async () => { await saveApplicationDetails(application.id, { ...form, state, rto, eligibility: "ready" }); return startDl(application.id); })}>{busy ? "Saving…" : "Continue to Driving Licence application →"}</Button></Frame>;
}

function DemoTools({ busy, onFastForward }: { busy: boolean; onFastForward: () => void }) {
  const [open, setOpen] = useState(false);
  return <div className="mt-10 border-t border-dashed border-gray-200 pt-4"><button type="button" onClick={() => setOpen(!open)} className="text-sm text-gray-400 hover:text-gray-600">DEMO / SIMULATION</button>{open && <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm text-amber-900">This demo action simulates the 30-day waiting period.</p><button disabled={busy} onClick={onFastForward} className="mt-3 w-full rounded-xl border border-amber-300 px-4 py-3 text-sm font-medium text-amber-950">Simulate 30 days →</button></div>}</div>;
}
