import { useEffect, useState } from "react";
import { type Application, advanceDelivery, bookAppointment, createDlPayment, getAppointmentSlots, issueDrivingLicence, saveDl, startDl, startDrivingTest, submitDrivingTest } from "../api/client";

interface Props { application: Application; onUpdated: (application: Application) => void; onNavigate: (page: string) => void; }
type ScreenProps = Omit<Props, "onUpdated"> & { busy: boolean; error: string | null; act: (work: () => Promise<{ application: Application }>) => Promise<void>; };
const tasks = ["Vehicle control", "Starting and stopping", "Turning safely", "Using signals", "Basic road awareness"];
const onNavigate = (page: string) => { if (page === "dashboard") window.history.back(); };

export default function DrivingLicenceFlow({ application, onUpdated, onNavigate }: Props) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const act = async (work: () => Promise<{ application: Application }>) => { setBusy(true); setError(null); try { const result = await work(); onUpdated(result.application); } catch (error) { setError(error instanceof Error ? error.message : "We couldn't save your journey right now."); } finally { setBusy(false); } };
  const props = { application, onNavigate, busy, error, act };
  if (!application.dl) return <Start {...props} />;
  if (application.currentStep === "dl-review") return <Review {...props} />;
  if (application.currentStep === "dl-payment") return <Payment {...props} />;
  if (application.currentStep === "dl-appointment") return <Appointment {...props} />;
  if (application.currentStep === "dl-rto-preparation") return <Preparation {...props} />;
  if (application.currentStep === "dl-driving-test") return <DrivingTest {...props} />;
  if (application.currentStep === "dl-driving-result") return <DrivingResult {...props} />;
  if (application.currentStep === "dl-delivery") return <Delivery {...props} />;
  return <Review {...props} />;
}

function Frame({ title, children, error }: { title: string; children: React.ReactNode; error?: string | null }) { return <div className="min-h-screen bg-white"><div className="max-w-2xl mx-auto px-5 pt-10 pb-24"><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Driving Licence journey</p><h1 className="mt-3 font-serif text-3xl text-gray-900 md:text-4xl">{title}</h1>{error && <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-5">{children}</div></div></div>; }
function Button({ children, onClick, disabled = false, secondary = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean; secondary?: boolean }) { return <button onClick={onClick} disabled={disabled} className={`mt-5 w-full rounded-xl px-5 py-3.5 text-base font-medium disabled:opacity-50 ${secondary ? "border border-gray-200 text-gray-700" : "bg-teal-600 text-white hover:bg-teal-700"}`}>{children}</button>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="mt-5 rounded-2xl border border-gray-200 p-5">{children}</div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-gray-100 py-3 text-sm last:border-none"><span className="text-gray-500">{label}</span><span className="text-right font-medium text-gray-900">{value}</span></div>; }

function Start({ application, busy, error, act }: ScreenProps) { return <Frame title="You can now apply for your Driving Licence" error={error}><p className="text-base leading-relaxed text-gray-600">You shouldn't have to enter the same information twice. We’ll carry forward your learner journey and ask you to review it.</p><Card><p className="text-sm text-gray-600">Your existing Learner's Licence details will be used for this demo application.</p></Card><Button disabled={busy} onClick={() => act(() => startDl(application.id))}>Continue with carried-forward details →</Button></Frame>; }
function Review({ application, busy, error, act }: ScreenProps) { const data = application.dl?.data || {}; const [name, setName] = useState(data.name || ""); const [address, setAddress] = useState(data.address || ""); const [vehicle, setVehicle] = useState(data.vehicle || ""); return <Frame title="Review your Driving Licence application" error={error}><p className="text-base leading-relaxed text-gray-600">Please check that your details are correct. Your Learner's Licence record and completed document checklist are carried forward.</p><Card><label className="block text-sm font-medium text-gray-700">Full name<input value={name} onChange={(e) => setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal" /></label><label className="mt-4 block text-sm font-medium text-gray-700">Address<input value={address} onChange={(e) => setAddress(e.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal" /></label><label className="mt-4 block text-sm font-medium text-gray-700">Vehicle class<input value={vehicle} onChange={(e) => setVehicle(e.target.value)} className="mt-1.5 w-full rounded-xl border border-gray-200 px-4 py-3 text-base font-normal" /></label><Detail label="Learner's Licence" value={data.learnerReference || "LL-DEMO-EXISTING"} /><Detail label="State / RTO" value={`${data.state || application.state || "To confirm"} · ${data.rto || application.rto || "To confirm"}`} /><Detail label="Documents" value="Carried forward demo checklist" /></Card><Button disabled={busy || !name || !address || !vehicle} onClick={() => act(() => saveDl(application.id, { name, address, vehicle }))}>{busy ? "Saving…" : "Continue to demo fee →"}</Button></Frame>; }
function Payment({ application, busy, error, act }: ScreenProps) { const [method, setMethod] = useState("UPI"); const [fail, setFail] = useState(false); const payment = application.dl?.payment; if (payment?.status === "successful") return <Appointment {...{ application, busy, error, act, onNavigate: () => {} }} />; return <Frame title={payment?.status === "failed" ? "Payment wasn't confirmed" : "Driving Licence demo payment"} error={error}>{payment?.status === "failed" ? <><Card><p className="text-sm text-gray-600">Do not pay again until you check the transaction status. Reference: <strong>{payment.reference}</strong>.</p></Card><Button disabled={busy} onClick={() => act(() => createDlPayment(application.id, method, "successful"))}>Retry demo payment →</Button></> : <><p className="text-base text-gray-600">Demo payment — no real money will be charged.</p><Card><Detail label="Driving Licence application" value="₹500" /><Detail label="Test/service fee" value="₹200" /><Detail label="Demo service charge" value="₹50" /><Detail label="Total" value="₹750" /></Card><div className="mt-5 space-y-2">{["UPI", "Card", "Net banking"].map((item) => <label key={item} className="flex gap-3 rounded-xl border border-gray-200 p-4 text-sm"><input type="radio" checked={method === item} onChange={() => setMethod(item)} />{item}</label>)}</div><label className="mt-4 flex gap-3 text-sm text-gray-700"><input type="checkbox" checked={fail} onChange={(e) => setFail(e.target.checked)} />Demo: simulate failed payment first</label><Button disabled={busy} onClick={() => act(() => createDlPayment(application.id, method, fail ? "failed" : "successful"))}>{busy ? "Processing…" : "Pay ₹750 (simulated) →"}</Button></>}</Frame>; }
function Appointment({ application, busy, error, act }: ScreenProps) { const [slots, setSlots] = useState<string[]>([]); const [slot, setSlot] = useState(""); useEffect(() => { void getAppointmentSlots().then(({ slots }) => { setSlots(slots); setSlot(slots[0] || ""); }).catch(() => {}); }, []); const appointment = application.dl?.appointment; if (appointment?.status === "booked") return <Preparation {...{ application, busy, error, act, onNavigate: () => {} }} />; return <Frame title="Book your driving-test appointment" error={error}><p className="text-base leading-relaxed text-gray-600">Appointment availability and online booking options may vary by state/RTO.</p><Card><p className="font-semibold text-gray-900">{application.dl?.data.rto || application.rto || "Your RTO"}</p><div className="mt-4 space-y-2">{slots.map((item) => <label key={item} className="flex gap-3 rounded-xl border border-gray-200 p-4 text-sm"><input type="radio" checked={slot === item} onChange={() => setSlot(item)} />{item}</label>)}</div></Card><Button disabled={busy || !slot} onClick={() => act(() => bookAppointment(application.id, slot))}>Confirm demo appointment →</Button></Frame>; }
function Preparation({ application, busy, error, act }: ScreenProps) { const appointment = application.dl?.appointment; return <Frame title="Before you go to the RTO" error={error}><p className="text-base leading-relaxed text-gray-600">Some parts of the Driving Licence process require an in-person RTO visit.</p><Card><ul className="space-y-3 text-sm leading-relaxed text-gray-700"><li>✓ Learner's Licence details</li><li>✓ Original required documents</li><li>✓ Appointment confirmation: {appointment?.slot || "Demo slot"}</li><li>✓ Application reference: {application.id}</li><li>✓ Appropriate vehicle for the driving test</li><li>✓ Any state/RTO-specific requirements</li></ul></Card><button onClick={() => window.print()} className="mt-4 w-full rounded-xl border border-gray-200 p-3 text-sm font-medium text-gray-700">Print demo appointment confirmation</button><Button disabled={busy} onClick={() => act(() => startDrivingTest(application.id))}>Start demo driving test →</Button></Frame>; }
function DrivingTest({ application, busy, error, act }: ScreenProps) { const [checks, setChecks] = useState<boolean[]>(Array(5).fill(false)); const toggle = (index: number) => { const next = [...checks]; next[index] = !next[index]; setChecks(next); }; return <Frame title="Driving competence test — Demo" error={error}><p className="text-base leading-relaxed text-gray-600">This simple simulation does not assess driving ability. In a real test, an authorised examiner determines the outcome.</p><Card>{tasks.map((task, index) => <label key={task} className="flex gap-3 border-b border-gray-100 py-3 text-sm text-gray-700 last:border-none"><input type="checkbox" checked={checks[index]} onChange={() => toggle(index)} className="h-5 w-5 accent-teal-600" />{task}</label>)}</Card><Button disabled={busy} onClick={() => act(() => submitDrivingTest(application.id, checks))}>{busy ? "Scoring…" : "Submit demo test →"}</Button></Frame>; }
function DrivingResult({ application, busy, error, act }: ScreenProps) { const test = application.dl?.drivingTest; if (!test) return <Preparation {...{ application, busy, error, act, onNavigate: () => {} }} />; if (!test.passed) return <Frame title="Your test needs another attempt" error={error}><p className="text-base leading-relaxed text-gray-600">You completed {test.score} of {test.total} simulated checks. Practise vehicle control, signalling, and safe manoeuvring. A real retest process can vary by state/RTO.</p><Button disabled={busy} onClick={() => act(() => startDrivingTest(application.id))}>Practise again / retry demo →</Button><Button secondary onClick={() => window.print()}>View RTO/retest guidance</Button></Frame>; return <Frame title="Driving test passed" error={error}><p className="text-base leading-relaxed text-gray-600">Your Driving Licence is now moving to the issuance stage in this simulation.</p><Card><p className="text-sm text-gray-700">✓ Test passed<br />○ Licence issued<br />○ Printed<br />○ Dispatched<br />○ Delivered</p></Card><Button disabled={busy} onClick={() => act(() => issueDrivingLicence(application.id))}>Issue Driving Licence — Demo →</Button></Frame>; }
function Delivery({ application, busy, error, act }: ScreenProps) { const licence = application.dl?.licence; if (!licence) return <DrivingResult {...{ application, busy, error, act, onNavigate: () => {} }} />; const sequence = ["issued", "printed", "dispatched", "delivered"] as const; const current = sequence.indexOf(licence.deliveryStatus); return <Frame title={licence.deliveryStatus === "delivered" ? "Your driving licence journey is complete." : "Driving Licence issued — Demo"} error={error}><Card><p className="text-xs font-semibold tracking-widest text-teal-700">DEMO / SIMULATED</p><h2 className="mt-2 text-xl font-semibold text-gray-900">{licence.reference}</h2><p className="mt-2 text-sm text-gray-600">{application.dl?.data.name || application.details.name || "Demo applicant"} · {application.dl?.data.vehicle || application.details.vehicle || "Vehicle class"}</p></Card><ol className="mt-6 space-y-3">{sequence.map((step, index) => <li key={step} className={`rounded-xl border p-4 text-sm ${index <= current ? "border-teal-200 bg-teal-50 text-teal-900" : "border-gray-200 text-gray-500"}`}>{index <= current ? "✓" : "○"} Licence {step}</li>)}</ol><p className="mt-5 text-sm leading-relaxed text-gray-600">This is a simulated licence record for the hackathon prototype. No government licence has been issued.</p><button onClick={() => window.print()} className="mt-4 w-full rounded-xl border border-gray-200 p-3 text-sm font-medium text-gray-700">Print / Download demo</button>{licence.deliveryStatus !== "delivered" && <Button disabled={busy} onClick={() => act(() => advanceDelivery(application.id))}>{busy ? "Updating…" : `Mark as ${sequence[current + 1]} — Demo`}</Button>}<Button secondary onClick={() => onNavigate("dashboard")}>Return to My Journey</Button></Frame>; }
