import { useState } from "react";
interface Props { onNavigate: (page: string) => void; }
const resources = [
  ["journey", "How the licence journey works", "Start with the Learner's Licence, complete the waiting period, then continue to the Driving Licence stage. Some steps require an RTO visit."],
  ["documents", "Documents you may need", "Prepare clear identity, address, age, photograph and signature evidence as applicable. Exact requirements can vary by state/RTO."],
  ["ll", "Learner's Licence guide", "Choose your vehicle class, complete your application and payment, then prepare for the learner test. The demo journey makes each next action clear."],
  ["dl", "Driving Licence guide", "After the learner-stage waiting period, review carried-forward details, pay the demo fee, book a driving-test appointment and attend the RTO stage."],
  ["signs", "Road signs", "Mandatory signs tell you what you must do; cautionary signs warn about hazards; informatory signs help you navigate. Always follow current local signs."],
  ["practice", "Practice test", "Try the Learner's Licence practice questions from the application journey. It is a learning tool, not an official question bank."],
  ["rto", "RTO visit checklist", "Carry your learner-licence details, originals required by your state/RTO, appointment confirmation, application reference and an appropriate vehicle where required."],
  ["driving", "Driving-test preparation", "Practise vehicle control, starting and stopping, turning, signalling, awareness and safe manoeuvring. An authorised examiner determines real test outcomes."],
  ["fees", "Fees and payments", "Amounts shown in Saarthi are simulated. Do not treat them as official fees. Keep a reference and do not retry a real payment before checking its status."],
  ["faq", "Common problems / FAQs", "Rejected document? Replace a clear copy. Payment uncertain? Check the reference first. Unsure what is next? Open My Journey for your saved current step."],
] as const;
export default function Resources({ onNavigate }: Props) { const [active, setActive] = useState<typeof resources[number] | null>(null); return <div className="min-h-screen bg-white"><div className="max-w-5xl mx-auto px-5 pt-14 pb-24"><p className="text-xs font-semibold tracking-widest text-teal-600 uppercase mb-4">Learning Centre</p><h1 className="font-serif text-3xl md:text-4xl text-gray-900 mb-3">Resources</h1><p className="text-base text-gray-600 max-w-xl">Plain-language guidance for the demo journey. State/RTO requirements and availability can vary.</p><div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{resources.map((resource) => <button key={resource[0]} onClick={() => setActive(resource)} className="min-h-40 rounded-2xl border border-gray-200 bg-white p-5 text-left hover:border-teal-300 focus:outline-none focus:ring-2 focus:ring-teal-500"><span className="text-xs font-semibold text-teal-700">GUIDE</span><h2 className="mt-3 text-base font-semibold text-gray-900">{resource[1]}</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">Open guide →</p></button>)}</div>{active && <div role="dialog" aria-modal="true" aria-labelledby="resource-title" className="fixed inset-0 z-50 flex items-end bg-gray-900/30 p-4 sm:items-center sm:justify-center"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><p className="text-xs font-semibold text-teal-700">SARATHI GUIDE</p><h2 id="resource-title" className="mt-2 font-serif text-2xl text-gray-900">{active[1]}</h2><p className="mt-4 text-base leading-relaxed text-gray-700">{active[2]}</p><button onClick={() => setActive(null)} className="mt-6 w-full rounded-xl bg-teal-600 px-5 py-3 text-base font-medium text-white">Close guide</button></div></div>}<div className="mt-14 rounded-2xl bg-teal-600 p-6 text-white"><h2 className="text-lg font-semibold">Ready to apply?</h2><p className="mt-1 text-sm text-teal-100">Start the saved journey, or return to My Journey if you are already signed in.</p><button onClick={() => onNavigate("entry")} className="mt-4 rounded-xl bg-white px-5 py-3 text-sm font-medium text-teal-700">Apply for a Licence →</button></div></div></div>; }
